### PR TITLE
added flask "hello world"

### PR DESCRIPTION
**Pull request by lombardero**
Provided the basic flask service for our service. It simply prints a welcome message when the Flask server is called.

We can use it to start building the complete service.

### CODE REVIEW

**Review by sflechas — COMMENTED** [review]
Looks good!

**Review by sflechas — APPROVED** [review]
Looks good.

**Comment by nisargthakkar** [comment]
I don't think we need HTML. Shouldn't our API only return JSON?

**Comment by lombardero** [comment]
Oh! You may be right, I am actually not sure. I was thinking it should have some sort of user interphase in the browser. Should I change it back to json?

**Comment by nisargthakkar** [comment]
It actually looks good for now. We can update it in the next PR.

**Comment by sflechas** [comment]
I checked with the professor and it needs to be only JSON.  @lombardero, could you please adjust it? Thanks!

**Comment by nisargthakkar** [comment]
Would you guys mind if I made these changes along with setting up the tests?

@lombardero have you started working on this already?

**Comment by lombardero** [comment]
I have started, let me do the pull request.

**Comment by nisargthakkar** [comment]
Cool. Thanks. Also, while you're at it, can you also move the files inside a `service` folder to stay consistent with the `lab-flask-rest`. I know I had told earlier that we can keep it in the main folder, but putting code inside a folder seems the better way now.

**Comment by lombardero** [comment]
Ok.

**Pull request merged**
