### PR TITLE
Adding testing code

### PR DESCRIPTION
**Pull request by nisargthakkar**
Current coverage report:
```
Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
service/__init__.py      20      3    85%   47-50
service/models.py        32      0   100%
service/service.py       57     21    63%   43, 48-50, 57-59, 66-68, 75-77, 84-86, 112-115, 132
---------------------------------------------------
TOTAL                   109     24    78%
```

The uncovered lines in `service/service.py` are the error handling and logging lines which will get covered once we implement the API.

### CODE REVIEW

**Comment by nisargthakkar** [comment]
I have one question, though. Should we be using the same database for tests and for code? (`wishlists` in this case.)

Since, in the tests, the DB is cleared and a new db is created

**Comment by sflechas** [comment]
The database is only created every time the vagrant file is provisioned, if it already exist, it wont delete it.  I think one db should be ok.

**Comment by nisargthakkar** [comment]
I meant clearing of tables. Like in this case:
https://github.com/nyu-devops-fall19-wishlists/wishlists/pull/50/files#diff-82e4cf48882d3e317ef6e7bdf284b059R49

So, all tables will get cleared on each test execution. And if we share the same database, it also affects the same tables that we use during development.

**Comment by sflechas** [comment]
I think it still ok, since we are not developing the UI, the only way to enter data during development is with the TDD cases, right?

**Comment by nisargthakkar** [comment]
Not really, we can use our API to make any changes to the database, or use some script to dump a set of data into it through mysql commands.

Everything we can do through the UI can be done through the API, just that it's not visually pleasing. This is where tools like Postman can help us. They provide the UI for REST API's.

As per the database, I'll just make changes and make a different test db as it really makes no sense to me to keep the same database for tests and actual code.

**Comment by sflechas** [comment]
The code inside the API should not write any data to the db except the piece where we implement sql alchemy, all the operations must be performed using that.  Additionally any data entered by the developer using Postman, is ok to be cleared before testing.  There is no need to create a 2nd db.

**Comment by nisargthakkar** [comment]
That's right. The code in the API will call the functions inside models to make any updates to the database. sqlalchemy isn't only for app startup. 

The controllers are the entrypoint to our REST API. They are the frontend html equivalent of backend microservices. If anyone wishes to make a web html out of this, they can either make the HTML rendering inside the controllers by calling `render` or they could create a separate microservice which doesn't talk to the database at all, but instead relies on the wishlists microservice. (Think of how we will be surfacing product details in our JSON response by invoking API's of the `products` microservice. We could very well have rendered HTML if we wanted to.)

Now regarding the two reasoning for having two databases. Right now, everyone is working on a VM and has a copy of the database. Some day, we have to move the database to the cloud. So, everyone shares the same database. Now let's say you are building some feature and you created some data to test it. It would be bad if I ran tests on my machine and cleared all the tables. Hence, the separate databases for test and dev.

**Comment by sflechas** [comment]
Yes, as discussed in class, the REST APIs work like that.  HTML is not part of this homework.  

As for the dbs, the database for development will not be uploaded to the cloud, each one of us will have a local copy, so you will be working on your local copy. I also checked this with Prof @rofrano.

image

We only need one db for this phase.

**Comment by nisargthakkar** [comment]
So, my question here is why not think ahead? Why add technical debt that we can clearly avoid? We will end up using tools like Travis CI which will run tests on the cloud.

**Comment by nisargthakkar** [comment]
Or we could do with one database but remove the requirements of dropping all tables and recreating them before every test. We can write tests which only delete the data they add

**Comment by sflechas** [comment]
Because it will be local, our work for this homework will be stored locally.  We can distribute the tasks different when we get to that point.

**Comment by nisargthakkar** [comment]
But I don't want data that I manually add to the db to be cleared without me explicitly telling it to

**Comment by sflechas** [comment]
if the data is deleted is only because you are testing, so you are actually telling it to do it. 
 And at that point it is best to start with an empty database.

**Comment by nisargthakkar** [comment]
That is true for tests. But not for development. I can choose to run tests any time during development. Why should it negatively affect my development environment?

**Comment by sflechas** [comment]
when doing TDD, you are testing the development you are doing, not the entire API, it will depend of what testing routines do you call while doing development, so you are in control of what is being tested.

**Comment by nisargthakkar** [comment]
Sorry. I refuse to go that route. The best I can do is to keep one db and remove the requirement of dropping tables.

I am ready to stand up and defend this to Prof. @rofrano as it literally doesn't make sense to drop all the tables before every test.

**Comment by nisargthakkar** [comment]
Also, even if I just test my API, when running any test, both tables will be dropped, so it does affect other components as well

**Comment by sflechas** [comment]
I don't think you are understanding the difference when testing when doing TDD, let's meet and discuss.

**Comment by sflechas** [comment]
Did you talk to Prof @rofrano?  I had already spoken to him, about this.  And he gave us a choice, but also said that for this class we don't need it, it is why I had told you that we are ok with only one db.  If you want to discuss, I'll be on campus until 4pm, and again tomorrow all day.  If not, please update the code back to use only one db.

**Comment by nisargthakkar** [comment]
That's ok. I'll take your suggestions as the product owner and revert to using one DB but I'm just letting you know this will curtail productivity and add technical debt which we will definitely have to address at a later time.

**Comment by sflechas** [comment]
All of that is part of the learning for this class.  Thank you for the heads up.

**Comment by lombardero** [comment]
Let's meet and discuss this in person.

From my side, I would feel more comfortable doing what the professor is asking us. Maybe it is not the most efficient way, but I do prefer following the class steps as they are set because I do not understand or have worked with most of the tools, and following along the class will be a much easier experience for me.

**Review by nisargthakkar — COMMENTED** [review]
I felt this change was not needed and it was only the password replacement for the database. I thought I was wrong and I closed this PR to modify that commit. GitHub doesn't let me reopen this. I opened another one #52

**Pull request closed without merging**
