### PR TITLE
Added minimal requirements.txt and Vagrantfile

### PR DESCRIPTION
**Pull request by nisargthakkar**

### CODE REVIEW

**Comment by nisargthakkar** [comment]
The Vagrantfile is almost the same as the one used in class. Only changes are the database - MySQL used. Due to this, I also had to allocate 2GB of RAM for the VM. 512 MB wasn't enough for mysql to start up

**Comment by wjduand** [comment]
How about install Pylint as well so that we can verify at any time and just in case it cannot be integrated with Github project.

**Comment by nisargthakkar** [comment]
Pylint had been added to requirements.txt which should install it on box setup. Does it not get installed currently? I can look into it.

**Comment by wjduand** [comment]
Sorry didn't notice that it should be fine.

**Comment by nisargthakkar** [comment]
Cool. np. Can you also LGTM?

**Review by wjduand — APPROVED** [review]
Looks good to me

**Pull request merged**
