### PR TITLE
minor changes in Readme routes

### PR DESCRIPTION
**Pull request by lombardero**
Some routes were not matching the RESTful service directives

### CODE REVIEW

**Comment by nisargthakkar** [comment]
I think we had changed them to plurals all across just to be consistent. As I remember from class, the professor mentioned we could still do it either way. I might be wrong. If this is a pattern that is followed, we could incorporate these changes.

@sflechas @wjduand any thoughts?

**Comment by sflechas** [comment]
I agree with @lombardero, after reading some documentation, plural is not the standard across the entire API, singular is used when it is an instance inside the collection.

**Comment by nisargthakkar** [comment]
cool. lets change merge this and also update the associated story also where we copied this from

**Review by nisargthakkar — APPROVED** [review]
LGTM

**Pull request merged**
