### PR TITLE
Updating mysql version to 5.7. Forwarded MySQL port to host.

### PR DESCRIPTION
**Pull request by nisargthakkar**
Before running `vagrant up --provision`, you might have to run the following:
* `vagrant ssh`
* `docker kill mysql && docker rm mysql && docker rmi mysql`
* Then exit vagrant and try `vagrant up --provision` again.

### CODE REVIEW

**Review by sflechas — COMMENTED** [review]
I am getting errors.
image

**Review by sflechas — CHANGES_REQUESTED** [review]
Please check the errors.

**Comment by nisargthakkar** [comment]
Added this to the initial message too, now.

Before running `vagrant up --provision`, you might have to run the following:
* `vagrant ssh`
* `docker kill mysql && docker rm mysql && docker rmi mysql`
* Then exit vagrant and try `vagrant up --provision` again.

**Review by sflechas — APPROVED** [review]
requires to run the commands before provisioning, refer back to the initial comment for details.

**Pull request merged**
