### PR TITLE
Added the Wishlists DB

### PR DESCRIPTION
**Pull request by sflechas**
To merge these changes to your local branch, execute these statements:
git checkout master
git pull
git checkout <your_feature_branch>
git merge master
vagrant up --provision

### CODE REVIEW

**Review by nisargthakkar — CHANGES_REQUESTED** [review]
The Vagrant provisioning looks good. Can you also add the database `.sql` file in this PR and you might also need to update the Vagrant file to set the schema from the sql file using sqlalchemy as John suggested on Slack?

**Comment by sflechas** [comment]
Did the wishlists db shows if you run ```show databases;``` after the provisioning?

**Comment by nisargthakkar** [comment]
I haven't tried it but I don't think it will. Since the mysql db is inside your Vagrant VM. Everyone has a separate copy of the database.

Everyone would share the database once we move the database to the cloud

**Comment by sflechas** [comment]
That is what I was asking Prof @rofrano, he said I only needed to update the vagrantfile.  Could you run the test? He said the --provision is supposed to download the schema.

**Comment by nisargthakkar** [comment]
I'll try it once. But I don't see from where it would download the schema. I think he meant that when we use sqlalchemy like here: https://github.com/nyu-devops/lab-flask-rest/blob/master/service/models.py#L51, the schema will get set up.

**Comment by nisargthakkar** [comment]
We still need the changes that you've made to the Vagrantfile for the persistence across restarts of the DB container and the VM

**Comment by sflechas** [comment]
could you please execute the command ```show databases;```? let me know what it returns.  The persistence was added to the vagrant file.  I also wanted to ask why are we running mysql V5.7, shouldn't we be running v8?

**Comment by nisargthakkar** [comment]
I am trying to run vagrant up and facing some issues on my machine. I don't think they're any code or config issues. Just looking into that. I'll update once I can run the command

**Comment by nisargthakkar** [comment]
The reason I downgraded to 5.7 was that in v8, mysql changed some authentication method and I couldn't connect to the DB/port forward. I didn't want to waste any more time behind that since it doesn't affect our application in any way

**Comment by sflechas** [comment]
ok, I will run the sqlalchemy configuration and update the PR

**Comment by nisargthakkar** [comment]
@sflechas I tried `vagrant up --provision`. Don't see the database schema in my machine.

I had a hard time understanding how the db gets set up using sqlalchemy. This page describes the flow: https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/#a-minimal-application

**Comment by nisargthakkar** [comment]
I don't know how this got merged. Sorry. These changes are self sufficient though for persistence of the database

**Comment by sflechas** [comment]
ok, no prob.  Yes, I found that article this morning and I am also comparing it to the exercise we did in class.  I'll update you later today.

**Comment by nisargthakkar** [comment]
Oh. This got merged because I merged @lombardero 's PR and he must have pulled your commits. Since the commits this PR suggested were all in, this seems to show as merged.

**Pull request merged**
