### PR TITLE
Adding testing code

### PR DESCRIPTION
**Pull request by nisargthakkar**
Current coverage report:
```
Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
service/__init__.py      20      3    85%   47-50
service/models.py        32      0   100%
service/service.py       57     21    63%   43, 48-50, 57-59, 66-68, 75-77, 84-86, 112-115, 132
---------------------------------------------------
TOTAL                   109     24    78%
```

The uncovered lines in `service/service.py` are the error handling and logging lines which will get covered once we implement the API.

This is almost the same as #50 which I had to close since I found a potential issue in my code. To fix that, I had to force-push (so I don't add random commits). Following that, GitHub doesn't let me reopen that PR. 

There is a detailed discussion on PR #50 regarding the choice of a separate database for dev and test. Refer to that for any comments. Further discussions might continue on this PR.

### CODE REVIEW

**Comment by sflechas** [comment]
I connected to the branch and I am trying to test the code but I am getting errors.  Could you post the instructions to test to make sure I am doing this right?  Thank you.

**Comment by nisargthakkar** [comment]
I run `nosetests --exe` (--exe only because I'm on Windows) and `coverage report -m` to get lines covered

**Comment by nisargthakkar** [comment]
Let me know if it still fails and also post the errors you see. I'll look into it.

**Comment by wjduand** [comment]
I got the same test report, but I run "Pylint tests" and got a score of 8.14. I think there are some minor problems like line too long which can be fixed.

**Comment by sflechas** [comment]
I am having problems with my local instance, @wjduand, if you agree and are comfortable with it, go ahead and merge.

**Review by sflechas — APPROVED** [review]
Looks good.

**Pull request merged**
